info:
    title: Bootcamp API
    version: 0.0.1
    description: REST API for Bootcamp project
host: localhost:3333
basePath: '/api'
swagger: '2.0'
paths:
    /auth/sign-in:
        post:
            description: Sign In User
            tags:
                - Auth
            produces:
                - application/json
            parameters:
                - $ref: '#/components/parameters/credentials'
            responses:
                200:
                    $ref: '#/components/responses/OK'
                401:
                    $ref: '#/components/responses/Unauthorized'

    /auth/sign-up:
        post:
            description: Sign Up User
            tags:
                - Auth
            produces:
                - application/json
            parameters:
                - $ref: '#/components/parameters/signup'
            responses:
                201:
                    $ref: '#/components/responses/OK'
                400:
                    $ref: '#/components/responses/BadRequest'
    /auth/logout:
        post:
            description: Logout
            tags:
                - Auth
            produces:
                - application/json
            responses:
                200:
                    $ref: '#/components/responses/OK'
                400:
                    $ref: '#/components/responses/BadRequest'
components:
    schemas:
        ResponseWithError:
            type: object
            description: Failed response result
            properties:
                message:
                    type: string
                code:
                    type: number
                    enum: [400, 404, 500, 403]
        ResponseWithMessage:
            type: object
            description: Success response result without data
            properties:
                message:
                    type: string
                code:
                    type: number
                    enum: [200, 201, 204]
        ResponseWithData:
            type: object
            description: Success response result with data
            properties:
                data:
                    oneOf:
                        - type: object
                        - type: array
                code:
                    type: number
                    enum: [200, 201]
    parameters:
        signup:
            name: signup
            description: create new user and sign in
            in: body
            require: true
            schema:
                type: object
                properties:
                    username:
                        type: string
                    first_name:
                        type: string
                    user_name:
                        type: string
                    birthdate:
                        type: string
                    password:
                        type: string
        credentials:
            name: credentials
            description: auth credentials
            in: body
            require: true
            schema:
                type: object
                properties:
                    username:
                        type: string
                    password:
                        type: string
    responses:
        BadRequest:
            description: Bad Request
            content: application/json
            schema:
                type: object
                '$ref': '#/components/schemas/ResponseWithError'
        Unauthorized:
            description: Unauthorized
            content: application/json
            schema:
                type: object
                '$ref': '#/components/schemas/ResponseWithError'
        OK:
            description: OK
            content: application/json
            schema:
                type: object
                $ref: '#/components/schemas/ResponseWithMessage'
tags:
    - name: Auth
      description: Authorization and Authentication
    - name: Project
      description: Projects
